### ISSUE TITLE
POLL: Shall we move away from this issue-system?

### ISSUE THREAD

**Issue by defaude** [eifion/asciicasts.com-translations#204]
Hey everyone.

First of all: Let me get a few words of gratitude out before I get to the point :) I know I've not contributed a lot (well, nothing, actually...) and am only really sometimes checking in, merging, commenting and closeing some pull requests and stuff. However, I'm totally blown away by your continued support for the project and by the many, many hours spent translating. I'm really happy about this!! Big kudos to all of you, seriously! "Will there be cake?" you ask? ;)

Anyways, let's get to it. The most important thing about collaborating in a project like ours is to make sure no effort is done redundantly - hence, in vain. It's always bad when some new fellas come along and start working on the translation of a new episode. Cool! But when they are ready to push their changes and see that it has already been done, they easily (and understandably) get frustrated and most likely leave. This was my reasoning for putting up the issue-based system. This way, it's easy to find out if there's already someone working on a specific episode's translation. However, this system has its flaws:
- The issue system is almost overflooding with these self-organisation issues
- These issues are not real _issues_ but markers instead
- Real issues (e.g. someone not in our team found a typo) easily get lost in the stream

Now for the _poll_: Do we want to abandon this issue-creating-coloring-closing thing and replace it with a wiki page? I think this would save a lot of effort for us _and_ for the users just floating by and looking at the overview which episode is available in which language. And the issue system would (finally) become a real issue system that is only used for real to-do issues... Please think about it and let me know in the comments below below, I'll check the responses in a few days (or weeks, maybe - you know me ^^)

Cheers,
Roland

**Comment by pantulis** [comment]
Using a wiki page would make more sense here, yes.  We could even have different wiki pages for the different efforts on different languages.

**Comment by whoshallsucceed** [comment]
+1

**Comment by nomfjmt** [comment]
I vote for a wiki.

**Comment by tomconvac** [comment]
Wiki sounds good to me as well.

**Comment by cogumm** [comment]
Use a wiki page!

**Comment by defaude** [comment]
closed by 6f55d5a577c9d061cf6f8a73370eda750b8f7384

**Comment by defaude** [comment]
Hi folks,

I just created some wiki pages for the major languages. (I just hope I got everything right...)

A few annotations here:
- The wiki syntax won't allow non-linear numbered lists so we need to include all empty entries where no **translated** or **pending** status is present
- I _think_ I got all languages and all their specific translations. However, could everyone please double-check that for their language? Thanks!
- The numbered list view might not be the best approach - if you're having a good idea, just let us all know! Or simply edit the wiki if it looks great ;)

Alright, that should do it. Thanks to all of you and have a nice weekend :D

## 

Roland

**Comment by pantulis** [comment]
I just changed the wiki page for the Spanish language, so that the most recent articles show up first and no scrolling is needed for the editions.
