### ISSUE TITLE
Episode 253 in Polish

### ISSUE THREAD

**Issue by tomconvac** [eifion/asciicasts.com-translations#206]
Started working on episode 253: CarrierWave

**Comment by defaude** [comment]
We never received that episode. Are you _still_ working on it? If you already finished, please just commit it to your repo and hit the "pull request" button there :)

**Comment by defaude** [comment]
bump?!

**Comment by tomconvac** [comment]
Sorry, I haven't noticed that. No, I'm not working on it. I have no time for it lately. Sorry for the inconvenience.

**Comment by defaude** [comment]
Don't worry - just cleaning up :)
