### ISSUE TITLE
Episode 236 translated in Italian 

### ISSUE THREAD

**Issue by acapilleri** [eifion/asciicasts.com-translations#237]
**Translation in Progress**

**Comment by defaude** [comment]
How's the translation coming along? Are you still working on it? ;)

**Comment by acapilleri** [comment]
Hi,
I'm fully immersed on my new work , so in the last period I can't working on.
But  few days, I hope have more time

Regards

Angelo

**Comment by defaude** [comment]
Hey Angelo,

Don't worry :) I was just cleaning up some old tickets (those things tend to stick around for quite some time...) so I was simply checking up on it. I myself couldn't find the time to contribute to the project at all during the past few months...

Cheers,
Roland

**Comment by acapilleri** [comment]
Ok Roland,
Have you ever think to extend asciicasts to use Wiki(Markdown) for episodes's updating ?

Angelo

**Comment by defaude** [comment]
Hey Angelo,

so damn sorry for not responding... We are "currently" thinking about our options for a future of asciicasts ;) See https://github.com/defaude/asciicasts.com-translations/issues/327
