### ISSUE TITLE
quote unclosed in the title of Japanese episode 274

### ISSUE THREAD

**Issue by nomfjmt** [eifion/asciicasts.com-translations#263]
Please close the quote at the end of the title of Japanese episode 274 as in episodes/000_summaries/summaries_ja.html.
Thanks.

**Comment by eifion** [comment]
Hello

Sorry, it was missed when I copied and pasted the title. It's fixed now.

Eifion

**Comment by nomfjmt** [comment]
Thanks, Eifion, for your quick response.
