### ISSUE TITLE
What about Railscasts Pro ?

### ISSUE THREAD

**Issue by simonc** [eifion/asciicasts.com-translations#295]
Hi,

What are we gonna do about the Railscasts Pro episodes ?
I guess we're not gonna write them down.
Maybe we could talk with Ryan to find a way to interact with railscasts to see if a user has subscribed.
I don't know if it worth it...

What do you think ?

**Comment by eifion** [comment]
Hello

Ryan's been in touch with me about the Pro episodes. He would like me to do ASCIIcast versions of them and for the regular translators to do translations, too. In return for you (and the other translators) providing translations of them he'll willing to give you free Pro subscriptions (presumably for as long as you carry on giving him translations).

Is this something you'd be interested in doing? I'm still working out the details with Ryan yet, but I'd be interested to know what you think of the idea.

Eifion

**Comment by simonc** [comment]
Hello,

As far as I'm concerned I think this is a great idea.
I paid for this month but that's ok, it could work for next month :)

Thanks for your answer :)

**Comment by nomfjmt** [comment]
Hi, 

I'm also happy with Ryan's offer, but I'm not sure if we could keep up with his pace on a voluntary basis as paying viewers 
would expect the transcripts to be published without fail and in time, let alone on a certain level of quality.

nomfjmt

**Comment by ulitiy** [comment]
Good idea of free pro for the translators. Thought about that.
And +1 for nomfjmt's comment, it could be difficult, but it is the great motivation for the translators :)

**Comment by defaude** [comment]
Hey everyone,

I think this is a great idea! However, I also see some problems for translators to keep up with Ryan - that guy provides sooooo much content :D

**Comment by nomfjmt** [comment]
And from when can we access Pro episodes?
Any update, Eifion?

**Comment by AndorChen** [comment]
Ryan releases one cast per week, then four a month, and the Pro account is charged once a month.

so, i think the translators should been given the Pro access for next month if, and only if, he/she translated at least two episodes for the current month.

**Comment by knightq** [comment]
How can we keep on translating old "reviewed" episodes if we have not a Pro Account?
Is Ryan going to release a per month Pro account to us or what else?
I could be interested in...

**Comment by arbox** [comment]
I have a Pro account, but it is reasonable to provide some kind of access for translators.

**Comment by knightq** [comment]
It would be great!
Let us now if and when it will be available!
