### ISSUE TITLE
Italian Summary description typo errors

### ISSUE THREAD

**Issue by knightq** [eifion/asciicasts.com-translations#55]
On episodes:
- 24: "quando di fa debugging" should be "quando si fa debugging".
- 25: "u'applicazione" should be "un'applicazione".
- 26: "l&rsquo;assegnamento" should be "l'assegnamento".
- 200: "niziare" should be "Iniziare".

**Comment by defaude** [comment]
Are those typos fixed already?

**Comment by defaude** [comment]
bump!?

**Comment by knightq** [comment]
Yes, they are.
Thank you!

**Comment by defaude** [comment]
Thanks, man :)
